POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMUBnb29nbGUuZmkiLCJpZCI6MSwiaWF0IjoxNjc1NDQ0NTIzfQ.hjDK4N9IT76f9Q0k62R2ulW2cZ0Az7HXdYkUEKZCTJU

{
    "author": "username1@google.fi",
    "url": "www",
    "title": "aaa",
    "likes": 5,
    "year": 2000
}